// It can feel overcomplicated to add the screen component here and then use it in the navigator.
// But it's for a reason, to ensure every newly added screen is automatically unit tested.

export {
  AboutYouScreen,
  AboutYourVaccineScreen,
  AdultOrChildScreen,
  AnniversaryScreen,
  ArchiveReasonScreen,
  BeforeWeStartUSScreen,
  ConfirmSchoolScreen,
  ConsentForOtherScreen,
  ConsentScreen,
  CovidTestConfirmScreen,
  CovidTestDetailScreen,
  CovidTestListScreen,
  CreateProfileScreen,
  DashboardScreen,
  DashboardUSScreen,
  DietStudyGlobalScreen,
  DietStudyGutScreen,
  DietStudyScreen,
  DietStudyTraditionalScreen,
  EditLocationScreen,
  EditProfileScreen,
  GeneralSymptomsScreen,
  GutStomachSymptomsScreen,
  HeadSymptomsScreen,
  HealthWorkerExposureScreen,
  HowYouFeelScreen,
  JoinHigherEducationScreen,
  JoinSchoolGroupScreen,
  JoinSchoolScreen,
  LongCovidQuestionScreen,
  LongCovidStartScreen,
  MHPGeneralScreen,
  MHPIntroductionScreen,
  MHPRatingScreen,
  MHPThankYouScreen,
  MediaCentreScreen,
  MentalHealthChangesScreen,
  MentalHealthEndScreen,
  MentalHealthFrequencyScreen,
  MentalHealthHistoryScreen,
  MentalHealthLearningScreen,
  MentalHealthSupportScreen,
  NursesConsentUSScreen,
  OptionalInfoScreen,
  OtherSymptomsScreen,
  PingdemicScreen,
  PreviousExposureScreen,
  PrivacyPolicySVScreen,
  PrivacyPolicyUKScreen,
  PrivacyPolicyUSScreen,
  ProfileBackDateScreen,
  ReconsentDiseasePreferencesScreen,
  ReconsentDiseaseSummaryScreen,
  ReconsentFeedbackScreen,
  ReconsentIntroductionScreen,
  ReconsentNewsletterSignupScreen,
  ReconsentReconsiderScreen,
  ReconsentRequestConsentScreen,
  RegisterScreen,
  ResetPasswordConfirmScreen,
  ResetPasswordScreen,
  SchoolDashboardScreen,
  SchoolGroupListScreen,
  SchoolHowToScreen,
  SchoolIntroScreen,
  SelectProfileScreen,
  SplashScreen,
  TermsOfUseUSScreen,
  ThankYouSEScreen,
  ThankYouUKScreen,
  ThankYouUSScreen,
  ThroatChestSymptomsScreen,
  TreatmentOtherScreen,
  TreatmentSelectionScreen,
  TrendlineScreen,
  VaccineDoseSymptomsScreen,
  VaccineFindInfoScreen,
  VaccineListScreen,
  VaccineLogSymptomsInfoScreen,
  Welcome1Screen,
  Welcome2Screen,
  WelcomeRepeatScreen,
  WhereAreYouScreen,
  YourHealthScreen,
  YourStudyScreen,
  YourWorkScreen,
} from '@covid/features';

export { CountrySelectScreen } from '@covid/features/CountrySelectScreen';
export { DataConsentScreen } from '@covid/features/wider-health-studies/screens/DataConsentScreen';
export { DiseasePreferencesScreen } from '@covid/features/wider-health-studies/screens/DiseasePreferencesScreen';
export { EstimatedCasesScreen } from '@covid/features/EstimatedCasesScreen';
export { LoginScreen } from '@covid/features/login/LoginScreen';
export { StudiesListScreen } from '@covid/features/studies-hub/screens/StudiesListScreen';
export { StudyDetailsScreen } from '@covid/features/studies-hub/screens/StudyDetailsScreen';
export { TestingModeScreen } from '@covid/features/testing-mode/TestingModeScreen';
export { WiderHealthStudiesScreen } from '@covid/features/wider-health-studies/screens/WiderHealthStudiesScreen';
