export default {
  border: 1,
  borderRadius: 4,
  borderRadiusBig: 16,
  buttonHeight: 56,
  drawerToggle: 20,
  maxScreenWidth: 600,
  screenHorizontalPadding: 24,
  screenVerticalPadding: 24,
  spacing: 16,
  spacingBig: 24,
  spacingHuge: 32,
  spacingSmall: 8,
  spacingTiny: 4,
};
